---
# tasks file
- name: Load a variable file based on the OS type
  include_vars: "{{ lookup('first_found', params) }}"
  vars:
      params:
          files:
              - "{{ansible_os_family}}.yaml"
          paths:
              - "vars"

- name: Install dependencies for installing
  package:
      name: "{{ item }}"
      state: present
  loop:
      - telnet
      - traceroute
      - curl
      - wget
      - htop
      - nano
      - gparted

- name: Firewall config open all port
  block:
      - name: UFW config
        include_tasks: ubuntu/ufw-cmd.yaml
        when: ansible_os_family == 'Debian'

      - name: Firewalld config
        include_tasks: redhat/firewalld-cmd.yaml
        when: ansible_os_family == 'RedHat'
